name: "Gtag"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    
jobs:
  terraform:
    uses: HappyPathway/centralized-actions/.github/workflows/terraform-test.yml@main
    with:
      terraform_version: ${{ vars.terraform_version }}
      terraform_api: ${{ vars.terraform_api }}
      github_username: ${{ github.actor }}
      github_email: ${{ github.actor }}@roknsound.com
      github_org: ${{ github.repository_owner }}
      setup_terraform: true
      terraform_init: true
      cache: ${{ github.workspace }}
      download_cache: true
      commit_sha: ${{ needs.setup-terraform.outputs.commit_sha }}
    secrets:
      TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

  gtag:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: terraform
    uses: HappyPathway/centralized-actions/.github/workflows/gtag.yml@main
    with:
      patch: true
      github_org: ${{ vars.GH_ORG }}
      github_username: ${{ vars.GH_USERNAME }}
      github_email: ${{ vars.GH_EMAIL }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
